/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package by.oznobishina.core;

import by.oznobishina.util.StringUtils;

public class Utils {
    public boolean isAllPositiveNumbers(String... str) {
        StringUtils stringUtils = new StringUtils();
        for (String s:str){
            if (!stringUtils.isPositiveNumber(s)) {
                return false;
            }
        }
        return true;
    }
}
